services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:14-alpine
    ports:
      - $EVENT_STORE_PORT:5432
    environment:
      - POSTGRES_DB=$EVENT_STORE_NAME
      - POSTGRES_USER=$EVENT_STORE_USER
      - POSTGRES_PASSWORD=$EVENT_STORE_PASSWORD
    volumes:
      - pg_event_data:/var/lib/postgresql/data
      - ./database/init_event_store.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    ports:
      - 8080:8080
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - EVENT_STORE_HOST=$EVENT_STORE_HOST
      - EVENT_STORE_NAME=$EVENT_STORE_NAME
      - EVENT_STORE_USER=$EVENT_STORE_USER
      - EVENT_STORE_PASSWORD=$EVENT_STORE_PASSWORD
      - EVENT_STORE_PORT=5432
    depends_on:
      - postgres
      - kafka
    command:
      [
        "bash",
        "-c",
        "while !</dev/tcp/postgres/5432; do sleep 1; done; while !</dev/tcp/kafka/9092; do sleep 1; done; uvicorn api.main:app --host 0.0.0.0 --port 8080 --reload",
      ]

  message_handler:
    build:
      context: ./message_handler
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - EVENT_STORE_HOST=$EVENT_STORE_HOST
      - EVENT_STORE_NAME=$EVENT_STORE_NAME
      - EVENT_STORE_USER=$EVENT_STORE_USER
      - EVENT_STORE_PASSWORD=$EVENT_STORE_PASSWORD
      - EVENT_STORE_PORT=5432
    depends_on:
      - postgres
      - kafka
    command:
      [
        "bash",
        "-c",
        "while !</dev/tcp/postgres/5432; do sleep 1; done; while !</dev/tcp/kafka/9092; do sleep 1; done; python -m message_handler.main",
      ]

  message_relay:
    build: ./message_relay
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$EVENT_STORE_HOST
      - DATABASE_PORT=5432
      - DATABASE_NAME=$EVENT_STORE_NAME
      - DATABASE_USER=$EVENT_STORE_USER
      - DATABASE_PASSWORD=$EVENT_STORE_PASSWORD
    depends_on:
      - postgres
      - kafka
    command:
      [
        "bash",
        "-c",
        "while !</dev/tcp/postgres/5432; do sleep 1; done; while !</dev/tcp/kafka/9092; do sleep 1; done; python -m message_relay.main",
      ]

volumes:
  pg_event_data:
