services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.1.10
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "messages:1:1"

  message_relay:
    build: ./message_relay
    depends_on:
      - kafka

    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - EVENT_STORE_DATABASE_HOST=$EVENT_STORE_DATABASE_HOST
      - EVENT_STORE_DATABASE_NAME=$EVENT_STORE_DATABASE_NAME
      - EVENT_STORE_DATABASE_USER=$EVENT_STORE_DATABASE_USER
      - EVENT_STORE_DATABASE_PASSWORD=$EVENT_STORE_DATABASE_PASSWORD

  message_handler:
    build:
      context: ./message_handler
      ssh:
        - default

    depends_on:
      - kafka

    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - EVENT_STORE_DATABASE_HOST=$EVENT_STORE_DATABASE_HOST
      - EVENT_STORE_DATABASE_NAME=$EVENT_STORE_DATABASE_NAME
      - EVENT_STORE_DATABASE_USER=$EVENT_STORE_DATABASE_USER
      - EVENT_STORE_DATABASE_PASSWORD=$EVENT_STORE_DATABASE_PASSWORD
