services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.1.10
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_IN://kafka:29092,LISTENER_OUT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN://kafka:29092,LISTENER_OUT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN:PLAINTEXT,LISTENER_OUT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN

  postgresql:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    depends_on:
      - kafka
    ports:
      - 8000:8000

  message_relay:
    build: ./message_relay
    depends_on:
      - kafka

    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD

  message_handler:
    build:
      context: ./message_handler
      ssh:
        - default
    extra_hosts:
      - host.docker.internal:host-gateway

    depends_on:
      - kafka

    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
