version: "3.8"
services:
  postgres_event:
    image: postgres:14-alpine
    ports:
      - $EVENT_DATABASE_PORT:5432
    environment:
      - POSTGRES_DB=$EVENT_DATABASE_NAME
      - POSTGRES_USER=$EVENT_DATABASE_USER
      - POSTGRES_PASSWORD=$EVENT_DATABASE_PASSWORD
    volumes:
      - pg_event_data:/var/lib/postgresql/data
      - ./database/init_event_store.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_query:
    image: postgres:14-alpine
    ports:
      - $QUERY_DATABASE_PORT:5432
    environment:
      - POSTGRES_DB=$QUERY_DATABASE_NAME
      - POSTGRES_USER=$QUERY_DATABASE_USER
      - POSTGRES_PASSWORD=$QUERY_DATABASE_PASSWORD
    volumes:
      - pg_query_data:/var/lib/postgresql/data
      - ./database/init_query_store.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.1.10
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_IN://kafka:29092,LISTENER_OUT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN://kafka:29092,LISTENER_OUT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN:PLAINTEXT,LISTENER_OUT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    build: ./api
    ports:
      - $API_PORT:$API_PORT

  message_relay:
    build: ./message_relay
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$EVENT_DATABASE_HOST
      - DATABASE_PORT=$EVENT_DATABASE_PORT
      - DATABASE_NAME=$EVENT_DATABASE_NAME
      - DATABASE_USER=$EVENT_DATABASE_USER
      - DATABASE_PASSWORD=$EVENT_DATABASE_PASSWORD
    depends_on:
      - postgres_event

  message_handler:
    build:
      context: ./message_handler
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$EVENT_DATABASE_HOST
      - DATABASE_PORT=$EVENT_DATABASE_PORT
      - DATABASE_NAME=$EVENT_DATABASE_NAME
      - DATABASE_USER=$EVENT_DATABASE_USER
      - DATABASE_PASSWORD=$EVENT_DATABASE_PASSWORD
    depends_on:
      - postgres_event

  read_manager:
    build:
      context: ./read_manager
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$QUERY_DATABASE_HOST
      - DATABASE_PORT=$QUERY_DATABASE_PORT
      - DATABASE_NAME=$QUERY_DATABASE_NAME
      - DATABASE_USER=$QUERY_DATABASE_USER
      - DATABASE_PASSWORD=$QUERY_DATABASE_PASSWORD
    depends_on:
      - postgres_query

volumes:
  pg_event_data:
  pg_query_data:

networks:
  my_network:
