version: "3.8"
services:
  postgres_event:
    image: postgres:14-alpine
    ports:
      - $EVENT_STORE_PORT:5432
    environment:
      - POSTGRES_DB=$EVENT_STORE_NAME
      - POSTGRES_USER=$EVENT_STORE_USER
      - POSTGRES_PASSWORD=$EVENT_STORE_PASSWORD
    volumes:
      - pg_event_data:/var/lib/postgresql/data
      - ./database/init_event_store.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_query:
    image: postgres:14-alpine
    ports:
      - $QUERY_STORE_PORT:5432
    environment:
      - POSTGRES_DB=$QUERY_STORE_NAME
      - POSTGRES_USER=$QUERY_STORE_USER
      - POSTGRES_PASSWORD=$QUERY_STORE_PASSWORD
    volumes:
      - pg_query_data:/var/lib/postgresql/data
      - ./database/init_query_store.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.1.10
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    build: ./api
    ports:
      - 8080:8000
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$QUERY_STORE_HOST
      - DATABASE_PORT=5432
      - DATABASE_NAME=$QUERY_STORE_NAME
      - DATABASE_USER=$QUERY_STORE_USER
      - DATABASE_PASSWORD=$QUERY_STORE_PASSWORD
    depends_on:
      - postgres_query

  message_relay:
    build: ./message_relay
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$EVENT_STORE_HOST
      - DATABASE_PORT=5432
      - DATABASE_NAME=$EVENT_STORE_NAME
      - DATABASE_USER=$EVENT_STORE_USER
      - DATABASE_PASSWORD=$EVENT_STORE_PASSWORD
    depends_on:
      - postgres_event

  message_handler:
    build:
      context: ./message_handler
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - EVENT_STORE_HOST=$EVENT_STORE_HOST
      - EVENT_STORE_PORT=5432
      - EVENT_STORE_NAME=$EVENT_STORE_NAME
      - EVENT_STORE_USER=$EVENT_STORE_USER
      - EVENT_STORE_PASSWORD=$EVENT_STORE_PASSWORD
    depends_on:
      - postgres_event

  read_manager:
    build:
      context: ./read_manager
    environment:
      - KAFKA_HOST=$KAFKA_HOST
      - DATABASE_HOST=$QUERY_STORE_HOST
      - DATABASE_PORT=5432
      - DATABASE_NAME=$QUERY_STORE_NAME
      - DATABASE_USER=$QUERY_STORE_USER
      - DATABASE_PASSWORD=$QUERY_STORE_PASSWORD
    depends_on:
      - postgres_query

volumes:
  pg_event_data:
  pg_query_data:
