services:
  message_relay:
    build: ./src/message_relay

    environment:
      - MESSAGE_OUTBOX_DATABASE_HOST=$MESSAGE_OUTBOX_DATABASE_HOST
      - MESSAGE_OUTBOX_DATABASE_NAME=$MESSAGE_OUTBOX_DATABASE_NAME
      - MESSAGE_OUTBOX_DATABASE_USER=$MESSAGE_OUTBOX_DATABASE_USER
      - MESSAGE_OUTBOX_DATABASE_PASSWORD=$MESSAGE_OUTBOX_DATABASE_PASSWORD
