import os

MESSAGE_OUTBOX_DATABASE_HOST = os.getenv("MESSAGE_OUTBOX_DATABASE_HOST")
MESSAGE_OUTBOX_DATABASE_NAME = os.getenv("MESSAGE_OUTBOX_DATABASE_NAME")
MESSAGE_OUTBOX_DATABASE_USER = os.getenv("MESSAGE_OUTBOX_DATABASE_USER")
MESSAGE_OUTBOX_DATABASE_PASSWORD = os.getenv("MESSAGE_OUTBOX_DATABASE_PASSWORD")
