import os

EVENT_STORE_DATABASE_HOST = os.getenv("EVENT_STORE_DATABASE_HOST")
EVENT_STORE_DATABASE_NAME = os.getenv("EVENT_STORE_DATABASE_NAME")
EVENT_STORE_DATABASE_USER = os.getenv("EVENT_STORE_DATABASE_USER")
EVENT_STORE_DATABASE_PASSWORD = os.getenv("EVENT_STORE_DATABASE_PASSWORD")

KAFKA_HOST = os.getenv("KAFKA_HOST")
